### ISSUE TITLE
Erstat "Hjælpetekst X" med faktisk hjælp

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/quiz#319]

**Comment by jorgenbech** [comment]
Hjælpetekster efter nummer:
1.	Link til quizzen. 
2.	Quizzens navn. Vises kun på administratorsiden
3.	Beskrivelse af quizzen. Vises kun her.
4.	Hvad handler quizzen om? Tags hjælper med at søge efter quizzer indenfor et særligt emne. 
5.	 ( Denne hjælpetekst vises på hele baggrundsbilledet - jeg kan ikke se hvad den faktisk hænger sammen med )
6.	(hvor?)
(7.	hvor?)
8.	(PROBLEM : denne tekst anvendes både i quizafslutningen og som tekst til hjælp knappen og til selve spørgsmålet. Disse tre ting skal da adskilles. ? )

**Comment by rasmuserik** [comment]
Jeg kigger på at rette teksterne i applikationen i morgen.

- Hjælpetekst 5 var tænkt til valg af baggrundsbillede (vi kan også bare droppe denne).
- Hjælpetekst 6 er ved valg af antal af point en given slutning giver
- Hjælpetekst 7 er ved pokalbillede
- Hjælpetekst 8 er vejledningen til tekst / markdown

(jeg har lavet udkast til indhold for 6, 7 og 8).

Forstår ikke helt "7. (PROBLEM...", hvilken tekst anvendes alle steder?

**Comment by rasmuserik** [comment]
Nu skulle hjælpeteksterne være rettede. Tager måske et øjeblik pga. caching at se dem.

Hjælpetekst 1, 2, 3 og 4, er som du skrev, bortset fra at jeg droppede "Vises kun på administratorsiden" fra 2'eren, da den også vises som titel i quizzen. 5 er slettet, og i 6, 7 og 8 lod jeg blot det udkast som jeg havde lavet stå som den faktiske tekst. Håber at det er ok, - ellers siger du bare hvad der skal ændres :)
