### ISSUE TITLE
Formattering af tekst

### ISSUE THREAD

**Issue by jorgenbech** [DBCDK/quiz#338]
Vil gerne kunne formattere teksten i både spørgsmål, hjæpetekst og i quizafslutningen. Måske bare i form af markdown? I hvert fald brug for at kunne gøre teksten større.

**Comment by rasmuserik** [comment]
Vi kan eventuelt gøre tekststørrelsen større - generelt i hele applikationen?

Formattering af tekst burde virke, - send gerne et eksempel hvor den ikke virker. Det kan også være en fejl ved formattering af teksten, - nogle gange glemmer jeg mellemrum mellem `#` og overskrifter, hvilket har følgende effekt:

```
##Overskrift
```

vil blive vist som

##Overskrift

(hvor det ser ud som om at det ikke virker), hvorimod at det rigtige er

```
## Overskrift
```

som vil blive vist som

## Overskrift
