### ISSUE TITLE
Problem med quizplatform

### ISSUE THREAD

**Issue by jorgenbech** [DBCDK/quiz#358]
Jeg prøvede at oprette en ny quiz. Nu viser den ingen quizzer i oversigten - først når jeg fx. søger på harry potter så dukker quizzen op. Jeg har prøvet at tømme cache og jeg har prøvet om søgefeltet er tomt - det er det.

**Comment by rasmuserik** [comment]
Jeg kigger på det med det samme!

Fejlen forekommer også her. Det er noget vi retter så hurtigt som muligt.

**Comment by rasmuserik** [comment]
@jorgenbech jeg har lagt en ny foreløbig udgave op, med et workaround omkring fejlen, så det forhåbentligt virker for dig igen?

Jeg vil lige dykke lidt mere ned i hvad der gik galt.
