### ISSUE TITLE
Kan ikke redigere billede i default quizafslutning

### ISSUE THREAD

**Issue by jorgenbech** [DBCDK/quiz#360]
Jeg kan ikke få lov til at tilføje billede i default quizafslutning. Alle andre steder virker det fint. Kan I rette det?

**Comment by rasmuserik** [comment]
Ja, - det får vi fikset :)

Satser på at det er ordnet i løbet af næste uge, - skriver opdateringer her når det er på plads.

**Comment by rasmuserik** [comment]
@jorgenbech nu burde det igen være muligt at redigere billeder i default quizafslutning. :)

**Comment by rasmuserik** [comment]
@jorgenbech test gerne, og giv også gerne lyd hvis der er andre ting som du støder på. PS: det er super at du opretter issues her på github, da det kommer lettere ind i mit workflow, og gør det enkelt at fikse / holde styr på de issues som der er :+1:

**Comment by jorgenbech** [comment]
Hej Rasmus

Nu kan jeg redigere i teksten i "default quizafslutning". Men jeg kan ikke uplade gifbilleder. Den vil godt tage almindelige billeder, men jeg har brugt en række animerede gif´er i løbet af quizzen. Disse kan ikke vises i default quizafslutning.

**Comment by rasmuserik** [comment]
Angående billeder, - så er der kun implementeret understøttelse af png og jpeg, på nuværende tidspunkt. Ved ikke om det var en del af projektet, også at have animerede billeder i quiz'en - udover filmklip. Tjekker lige op på dette, - og opretter evt. issue på gif-understøttelse i den åbne platform.

**Comment by rasmuserik** [comment]
Har oprettet issue i den åbne platform: dbcdk/serviceprovider#1022

**Comment by jorgenbech** [comment]
Det virkede jo rigtig fint for en uge siden :)

Jørgen Bech Pedersen
Cand.scient.bibl.
• 87 22 19 39
jbp@silkeborgbib.dk<mailto:jbp@silkeborgbib.dk>

[Beskrivelse: cid:image001.png@01CD2468.4794DF70]

Silkeborg Bibliotekerne
Hostrupsgade 41A • 8600 Silkeborg
87 22 19 00 • silkeborgbib.dk<http://silkeborgbib.dk/>

Fra: RasmusErik Voel Jensen [mailto:notifications@github.com]
Sendt: 12. februar 2019 20:31
Til: DBCDK/quiz <quiz@noreply.github.com>
Cc: Jørgen Bech Pedersen <jbp@Silkeborgbib.dk>; Mention <mention@noreply.github.com>
Emne: Re: [DBCDK/quiz] Kan ikke redigere billede i default quizafslutning (#360)


Angående billeder, - så er der kun implementeret understøttelse af png og jpeg, på nuværende tidspunkt. Ved ikke om det var en del af projektet, også at have animerede billeder i quiz'en - udover filmklip. Tjekker lige op på dette, - og opretter evt. issue på gif-understøttelse i den åbne platform.

**Comment by rasmuserik** [comment]
@jorgenbech virkede animerede gif-billeder, gemt i den åbne platform for 1½ uge siden?

Jeg sidder og laver ændringer i den åbne platform, for at prøve om hvor enkelt der er at få gif-billeder i storage-endpointet (inkl. skaleringe etc.), - men kan se at den underliggende software som vi bruger til at skalere billederne ikke understøtter animationer, - så jeg kan ikke forstå hvis det har virket tidligere (bortset fra hvis billederne ikke har været skaleret).

@BettinaAndersen hvad er dine tanker om hvordan vi håndterer gif-billeder i den åbne platform?

**Comment by rasmuserik** [comment]
Ah, - nå ja, det kan have virket hvis billederne ikke er blevet skaleret, - og det er de næppe hvis filformatet ikke har været genkendt.

MEN hvis gif-billederne skaleres, bliver de behandlet som statisk billeder og ikke animationer.

Jeg retter den åbne platform således at gif-billedformatet genkendes. Status for dette kan ses i ssue på den åbne platform: dbcdk/serviceprovider#1022

I første omgang behandles gif-billederne som statiske billeder hvis man forsøger at skalere dem, - men alternativt kan jeg også ændre koden således at gif-billeder i stedet ikke skaleres?

**Comment by jorgenbech** [comment]
Ingen skalering. Det er er netop animationen der liver quizzen gevaldigt op.

Jørgen Bech Pedersen
Cand.scient.bibl.
• 87 22 19 39
jbp@silkeborgbib.dk<mailto:jbp@silkeborgbib.dk>

[Beskrivelse: cid:image001.png@01CD2468.4794DF70]

Silkeborg Bibliotekerne
Hostrupsgade 41A • 8600 Silkeborg
87 22 19 00 • silkeborgbib.dk<http://silkeborgbib.dk/>

Fra: RasmusErik Voel Jensen [mailto:notifications@github.com]
Sendt: 18. februar 2019 11:52
Til: DBCDK/quiz <quiz@noreply.github.com>
Cc: Jørgen Bech Pedersen <jbp@Silkeborgbib.dk>; Mention <mention@noreply.github.com>
Emne: Re: [DBCDK/quiz] Kan ikke redigere billede i default quizafslutning (#360)


Ah, - nå ja, det kan have virket hvis billederne ikke er blevet skaleret, - og det er de næppe hvis filformatet ikke har været genkendt.

MEN hvis gif-billederne skaleres, bliver de behandlet som statisk billeder og ikke animationer.

Jeg retter den åbne platform således at gif-billedformatet genkendes. Status for dette kan ses i ssue på den åbne platform: DBCDK/serviceprovider#1022<https://github.com/DBCDK/serviceprovider/issues/1022>

I første omgang behandles gif-billederne som statiske billeder hvis man forsøger at skalere dem, - men alternativt kan jeg også ændre koden således at gif-billeder i stedet ikke skaleres?

**Comment by rasmuserik** [comment]
Vender tilbage i næste uge, - når jeg har vendt det med @BettinaAndersen  (da beslutningen berører den åbne platform generelt).

**Comment by jorgenbech** [comment]
Hej @rasmuserik - har I fået snakket om det?

**Comment by rasmuserik** [comment]
@jorgenbech - jeg har netop talt med Bettina, og fået grønt lys, - så jeg er i fuld gang med at implementerer det. Da det er en del af den åbne platform ligger issuet derovre: dbcdk/serviceprovider#1025
Satser på at det er ordnet senere i dag, eller i morgen.

**Comment by rasmuserik** [comment]
@jorgenbech - koden er rettet nu, - der går lidt tid endnu inden at det virker, da den nye udgave af den åbne platform med ændringen skal sættes i drift.

**Comment by rasmuserik** [comment]
Det burde være rettet nu, - du må meget gerne teste, og melde tilbage om det virker som ønsket?

**Comment by jorgenbech** [comment]
Den skriver  "unsupported screen" når jeg indsætter et billede (gif) i et spørgsmål og herefter klikker pil-tilbage.

**Comment by rasmuserik** [comment]
Tak for reminderen, - det kigger jeg på i #362 

Jeg var så fokuseret på at rette det med gif'erne, at jeg havde glemt at kigge på denne, som ikke ser ud til at have noget med gif-formatet at gøre.
