### ISSUE TITLE
Quizafslutning - stadig problemer

### ISSUE THREAD

**Issue by jorgenbech** [DBCDK/quiz#362]
Hej Rasmus

Der er stadig problemer med quizzen. 

Nu har den fjernet alle de animerede gif billeder jeg havde sat på alle spørgsmål og svar (de er i hvert fald ikke synlige) og jeg kan ikke få lov til at lægge dem på igen. Systemet vil dog gerne vise almindelige jpeg. Systemet fejler når man prøver at trykke "pil tilbage" og melder "Error: unsupported screen"

**Comment by rasmuserik** [comment]
Jeg tjekker op på dette (måske bliver det først efter vinterferien, i.e. næste uge).

**Comment by rasmuserik** [comment]
@jorgenbech nu burde den være rette, - du må meget gerne test og melde tilbage om alt er ok?

Det tog lidt længere tid inden den kom på plads, end jeg først havde regnet med, - beklager.

**Comment by jorgenbech** [comment]
Tak :) Det ser umiddelbart ud til at virke fint det hele.

Jørgen Bech Pedersen
Cand.scient.bibl.
• 87 22 19 39
jbp@silkeborgbib.dk<mailto:jbp@silkeborgbib.dk>

[Beskrivelse: cid:image001.png@01CD2468.4794DF70]

Silkeborg Bibliotekerne
Hostrupsgade 41A • 8600 Silkeborg
87 22 19 00 • silkeborgbib.dk<http://silkeborgbib.dk/>

Fra: RasmusErik Voel Jensen [mailto:notifications@github.com]
Sendt: 27. februar 2019 11:25
Til: DBCDK/quiz <quiz@noreply.github.com>
Cc: Jørgen Bech Pedersen <jbp@Silkeborgbib.dk>; Mention <mention@noreply.github.com>
Emne: Re: [DBCDK/quiz] Quizafslutning - stadig problemer (#362)


@jorgenbech<https://github.com/jorgenbech> nu burde den være rette, - du må meget gerne test og melde tilbage om alt er ok?

Det tog lidt længere tid inden den kom på plads, end jeg først havde regnet med, - beklager.
