### ISSUE TITLE
setup postgres server for openplatform and add config

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/quiz#45]
Den Åbne Platform (staging + prod) har brug for en postgres-database i forbindelse med storage-endpointet til quiz-projektet. Dette issue dækker:

- [ ] opsætning af databasen
- [ ] environment-variabel: PG_CONNECTION_STRING med server+credentials som gives med, når serviceprovideren kører.

**Comment by BettinaAndersen** [comment]
Erstattet af https://github.com/DBCDK/serviceprovider/issues/979
