### ISSUE TITLE
Deployment til quiz.dbc.dk

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/quiz#74]

**Comment by rasmuserik** [comment]
Indholdet fra `gh-pages`-branchen skal svjv. hostes under dbc-domænet, - evt. med egen server via kubernetes, og opdateres når der kommer et nyt push til branchen (som vi talte om i dag, i stedet for at bruge githubs infrastruktur). Der kan sættes et hook op ved commits til `gh-pages`-branchen, hvorefter det kan udrulles automatisk. (Der deployes forøjeblikket til gh-pages, hvilket automatisk ligger online på https://dbcdk.github.io/quiz/.
